services:
  web:
    build: .
    container_name: recircle_backend
    env_file: .env
    environment:
      - PYTHONPATH=/app
    ports:
      - '5000:5000'
    command: sh /docker-entrypoint.sh
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: recircle_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: LittleCircle1
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'

  migrate:
    build: .
    container_name: recircle_backend_migrate
    command: ['sh', '/docker-entrypoint.sh', 'migrate']
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  postgres_data:
